### ISSUE TITLE
动态注入的js内容怎么查看？

### ISSUE THREAD

**Issue by lzqjfly** [seven456/SafeWebView#1]
仁兄好，请教个问题：
通过view.loadUrl("javascript:(function(b){var host = {name:'test'};b.host = host;}(window)))将注入js，这些注入的js被注入到哪儿了？在body里的js里面直接访问host.name会提示host is not defined。怎样才能保证在解析js里面的内容是已经完成js的注入

**Comment by seven456** [comment]
view.loadUrl(js)需要在各个地方尽量多的注入（onProgressChanged），并且js本身需要自己判断是否注入成功避免重复创建（参考项目中的notRepeat.js）；
